version: '3.1'

services:
  
  node-app:
    image: node-mongo
    build: .
    restart: always
    ports:
      - 4000:4000

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes: 
    - mongo-db:/data/db

volumes:
  mongo-db: